name: main

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Build Package
        run: |
          echo "Build commands go here"
          # e.g. npm install, make, etc.

  code-scan:
    name: Code Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run code scan
        run: |
          echo "Run code scanning tools here"
          # e.g. npm audit, static analysis tools, etc.

  test:
    name: Automated Test
    runs-on: ubuntu-latest
    needs: code-scan
    steps:
      - name: Automated Test
        run: |
          echo "Run tests here"
          # e.g. npm test, pytest, etc.

  change: 
    name: Change Control
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Change Control
        uses: ServiceNow/servicenow-devops-change@v6.0.0
        id: create
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Change Control'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"change created from github"}}'
          interval: '100'
          timeout: '3600'
          abortOnChangeCreationFailure: true
          abortOnChangeStepTimeout: true
      - name: Output of Change Creation
        run: echo "change-request-number = ${{ steps.create.outputs.change-request-number }} and change-request-sys-id = ${{ steps.create.outputs.change-request-sys-id }} " >> $GITHUB_OUTPUT
          

  deploy:
    runs-on: ubuntu-latest
    needs: change
    if: github.ref == 'refs/heads/main'
    steps:   
      - name: Run Deployment Script
        run: echo "Deployment Finished....."
